BranchAndLink/GoLangFastPaced

examples/mohsun/Output.go

Exi gor duzgun yere push elemishem?

Output notes submission

---

examples/mohsun/FlowControls.go

Flow controls

---

examples/mohsun/Arrays.go

Salamaleykum. Buna bax gor exi, yeni branchden push eledim

Mohsun array 68

---

examples/mohsun/Slices.go

Slice-i da push edirem exi, zehmet olmasa baxarsan.

mohsun_slice_71

---

examples/mohsun/Functions.go

Salamaleykum exi. Buna baxarsan zehmet olmasa.

mohsun_function_64

---

lectures/az/abdelrauf/Pointers.ipynb
website/GoFastPaced/content/posts/Pointers_abdelrauf.md

issue145 pointers

---

examples/mohsun/StringNumber.go

Salamaleykum exi, zehmet olmasa bunu review edersen. En axirda ASCII den cevirme ile bagli da bir dene numune yazmisham.

mohsun_stringnumber_44

---

website/GoFastPaced/content/posts/Error_defer_panic_recover_abdelrauf.md

error,panic,defer,recover

---

examples/mohsun/pointers.go

mohsun_pointers_147

---

examples/mohsun/Structs.go

mohsun_struct_133

---

lectures/az/abdelrauf/GoroutineChannelsSelectWaitGroup.ipynb
website/GoFastPaced/content/posts/GoroutineChannelsSelectWaitGroup_abdelrauf.md

goroutine #185

---

examples/mohsun/Maps.go

mohsun_map_78

---

examples/mohsun/Interface.go

mohsun_interface_137

---

examples/mohsun/anonym_closure.go

mohsun_anonymousfunc_157

---

examples/mohsun/Generics.go

mohsun_generics_168

---

examples/mohsun/DeferPanic.go

mohsun_defer_panic_162

---

examples/mohsun/Goroutine.go
examples/mohsun/Select.go

mohsun_goroutine_186

---

examples/1kanony/arrays_and_slice.go

arrays and slice

---

examples/1kanony/type_and_struct.go

type and struct

---

examples/1kanony/interfaces_generics.go

interfaces & generics
